### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [lichess-org/lila-ws#414]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by ornicar** [comment]
They probably would all work for the simple use case we have. I made that choice many years ago and have not looked at other solutions ever since. Therefore I can't make any recommendation about this choice.
