### ISSUE TITLE
Platform independent build configuration

### ISSUE THREAD

**Issue by ckoopmann** [lichess-org/lila-ws#72]
So when I was trying to get the websockets working for the first time on macos I spent quite a lot of time with reactivemongo errors caused by [this line](https://github.com/ornicar/lila-ws/blob/master/build.sbt#L17) in the build file.

I was wondering if it might be possible / a good idea to have an os-agnostic build file maybe doing something like [this](https://stackoverflow.com/questions/55591045/sbt-dynamically-detect-building-platform).

**Comment by shawninder** [comment]
@ckoopmann I am getting an error I believe you got in the past. I tried the solution you mentioned [here](https://discord.com/channels/280713822073913354/693123750845218836/706063857042325554), adapting it for a more recent version of lila by instead modifying [this line](https://github.com/ornicar/lila/blob/master/project/Dependencies.scala#L49), but for me it didn't work.

To be more precise, I can launch lila, visit localhost:9663 with 2 browser windows, start a game with one window and join it with the other. Only when white moves, black is never notified.

I'm just curious whether you knew anything more about this that could help me as I'm not sure where to go from here...

**Comment by gabbard** [comment]
I am also suffering from exactly this issue.

**Comment by gabbard** [comment]
I was able to fix it by changing the `reactivemongo` line to:
```
libraryDependencies += "org.reactivemongo"           % "reactivemongo-shaded-native"  % s"$reactivemongoVersion-osx-x86-64"
```

**Comment by thiloplanz** [comment]
Running on an ARM-based M1 Mac, I had to comment out that line.

´´´
// libraryDependencies += "org.reactivemongo"           % "reactivemongo-shaded-native"  % s"$reactivemongoVersion-osx-x86-64"
´´´

Without it, ReactiveMongo seems to fall back to an architecture-independent mechanism.
